# Generated by Django 6.0.2 on 2026-02-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='course',
        ),
        migrations.RemoveField(
            model_name='module',
            name='parent_module',
        ),
        migrations.RemoveIndex(
            model_name='resource',
            name='resources_r_univers_32369f_idx',
        ),
        migrations.RemoveIndex(
            model_name='resource',
            name='resources_r_year_6f5861_idx',
        ),
        migrations.AddField(
            model_name='university',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(help_text='e.g., CSC101', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(help_text='e.g., Introduction to Programming', max_length=200),
        ),
        migrations.AlterField(
            model_name='university',
            name='code',
            field=models.CharField(help_text="Short code like 'ub', 'biust'", max_length=20, unique=True),
        ),
        migrations.RemoveField(
            model_name='resource',
            name='course',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='module',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='resource_type',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='university',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='uploaded_by',
        ),
        migrations.DeleteModel(
            name='ResourceDownload',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
        migrations.DeleteModel(
            name='ResourceType',
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
    ]
