# Generated by Django 6.0.2 on 2026-02-18 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_resourcetype_module_resource_resourcedownload_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['-academic_year', 'course', 'resource_type'], 'verbose_name': 'Resource', 'verbose_name_plural': 'Resources'},
        ),
        migrations.AlterModelOptions(
            name='resourcedownload',
            options={'verbose_name': 'Resource Download', 'verbose_name_plural': 'Resource Downloads'},
        ),
        migrations.AlterModelOptions(
            name='resourcetype',
            options={'verbose_name': 'Resource Type', 'verbose_name_plural': 'Resource Types'},
        ),
    ]
